### ISSUE TITLE
Biosample XML script performs very slowly

### ISSUE THREAD

**Issue by ropolomx** [AAFC-Lethbridge-Bioinformatics-Support/beebiome-curation-scripts#4]
@lilicamd found out that commenting out this line makes the BioSample XML script perform much faster. It currently can take 27 hours to run, vs minutes when this is commented out.

https://github.com/AAFC-Lethbridge-Bioinformatics-Support/beebiome-curation-scripts/blob/b208fef828c1861e7da735ef128635b4338d25d9/biosample-xml-parse.py#L271

**Comment by lilicamd** [comment]
I was looking to troubleshoot the issue, but there ware few functions which I think were work in progress and took a long time to finish processing all the XML files. After I commented one line time improved, but results seems to be different. 

Instead, use the new curation Jupyter Notebook getCurationBiosamples.ipynb, an interactive process which helps to run the curation steps in less than one hour.
